# Generated by Django 5.0.2 on 2024-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('COOKING', 'Cooking'), ('TRAVEL', 'Travel'), ('GAMING', 'Gaming'), ('TECHNOLOGY', 'Technology'), ('ART', 'Art'), ('MEMES', 'Memes')], max_length=20, null=True),
        ),
    ]
